apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j-statefulset
  labels:
    app: neo4j    
spec:
  serviceName: neo4j
  selector:
    matchLabels:
      app: neo4j      
  template:
    metadata:
      labels:
        app: neo4j        
    spec:
      containers:
      - name: neo4j
        image: neo4j:4.4
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        env:
        - name: NEO4J_AUTH
          value: "neo4j/password"
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: neo4j-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: neo4j-logs
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  labels:
    app: neo4j    
spec:
  type: NodePort
  selector:
    app: neo4j    
  ports:
  - name: http
    protocol: TCP
    port: 7474
    targetPort: 7474
    nodePort: 30006
  - name: bolt
    protocol: TCP
    port: 7687
    targetPort: 7687
    nodePort: 30007
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neo4j-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: neo4j.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neo4j-service
            port:
              number: 7474
